version: '3.8'

services:

  db:
    image: mariadb:10.4
    container_name: jii2-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jii2-web
    ports:
      - "8880:80"
    volumes:
      - ./app/:/var/www/html
    depends_on:
      - db

#  test:
#    build: .
#    entrypoint: ["bash", "-c", "codecept run"]
#    depends_on:
#      - web
#    volumes:
#      - ./tests:/var/www/html/tests

